### ISSUE TITLE
PyPy / Py3 release

### ISSUE THREAD

**Issue by papachoco** [zopefoundation/zc.catalog#2]
Hi,

Is there an ETA for pypy/py3 release of this package? We look forward to use such new version.

Thanks

Carlos

**Comment by jamadden** [comment]
#1 looks like a good start. If no one else picks up the ball, I can take a look at it after I get zope.file done.

**Comment by jamadden** [comment]
This project has a (test) dependency on zope.app.catalog, which is not yet ported, but is also not in git. @jimfulton could you please bring zope.app.catalog into git?

**Comment by jimfulton** [comment]
Yup.

**Comment by jimfulton** [comment]
Done.  I suggest copying whatever it was depending on to get rid of the dependency.

**Comment by jamadden** [comment]
2.0 has been released to PyPI.
